import io
import os
from datetime import datetime
import math

import matplotlib.pyplot as plt

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image
)
from reportlab.lib.styles import getSampleStyleSheet
from matplotlib.ticker import FuncFormatter


def format_date_human(date_val):
    try:
        if isinstance(date_val, str):
            dt = datetime.fromisoformat(date_val.replace("Z", ""))
        else:
            dt = datetime.now()
    except:
        dt = datetime.now()

    return dt.strftime("%d %B %Y")  


def normalize_explanation(explanation):
    if isinstance(explanation, str):
        return explanation.strip()
    if isinstance(explanation, dict):
        return (
            explanation.get("content")
            or explanation.get("summary")
            or explanation.get("message")
            or ""
        ).strip()
    return ""


def generate_biomarker_chart(tests):
    labels, values = [], []

    for t in tests:
        try:
            v = float(t.get("value"))
            if v <= 0:
                continue
            labels.append(t.get("test_name", "").replace("_", " ").title())
            values.append(v)
        except:
            continue

    if not values:
        return None

    max_val = max(values)
    min_val = min(values)

    
    use_log = min_val > 0 and (max_val / min_val) > 20

    fig, ax = plt.subplots(figsize=(7, 4))

    ax.bar(labels, values, color="#60a5fa")

    if use_log:
        ax.set_yscale("log")
        ax.set_ylabel("Value (scaled for readability)")

        
        ax.yaxis.set_major_formatter(
            FuncFormatter(lambda y, _: f"{int(y)}")
        )
    else:
        ax.set_ylabel("Value")

    ax.set_title("Smart Health Visualization")
    ax.tick_params(axis="x", rotation=40, labelsize=9)
    ax.grid(axis="y", linestyle="--", alpha=0.4)

    plt.tight_layout()

    buf = io.BytesIO()
    plt.savefig(buf, format="png", dpi=150)
    plt.close(fig)
    buf.seek(0)

    return buf


def draw_common_header(canvas, doc, report_data):
    width, height = letter

    canvas.setStrokeColor(colors.HexColor("#6b7280"))
    canvas.setLineWidth(1.6)
    canvas.rect(25, 25, width - 50, height - 50)

    logo_path = "assets/logo.jpeg"
    if os.path.exists(logo_path):
        canvas.drawImage(
            logo_path,
            40,
            height - 70,
            width=100,
            height=34,
            preserveAspectRatio=True,
            mask="auto"
        )

    date_str = format_date_human(report_data.get("created_at"))
    canvas.setFont("Helvetica", 10)
    canvas.setFillColor(colors.grey)
    canvas.drawRightString(
        width - 40,
        height - 45,
        f"Date: {date_str}"
    )

    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(
        width - 40,
        20,
        f"Generated by CareScore AI • Page {doc.page}"
    )


def draw_carescore(canvas, analysis_result):
    width, height = letter

    score = int(analysis_result.get("care_score") or 0)
    score = max(0, min(100, score))

    cx = width / 2
    cy = height - 75
    r = 28  

    if score >= 80:
        ring_color = colors.HexColor("#16a34a")
    elif score >= 50:
        ring_color = colors.HexColor("#f59e0b")
    else:
        ring_color = colors.HexColor("#dc2626")

    
    canvas.setLineWidth(5)
    canvas.setStrokeColor(colors.lightgrey)
    canvas.circle(cx, cy, r)

    
    canvas.setStrokeColor(ring_color)
    canvas.arc(
        cx - r, cy - r,
        cx + r, cy + r,
        startAng=90,
        extent=-360 * (score / 100)
    )

    
    canvas.setFont("Helvetica-Bold", 14)
    canvas.setFillColor(colors.black)
    canvas.drawCentredString(cx, cy - 5, str(score))

    
    canvas.setFont("Helvetica-Bold", 10)
    canvas.setFillColor(colors.grey)
    canvas.drawCentredString(cx, cy - r - 14, "CareScore")


def draw_first_page(canvas, doc, report_data, analysis_result):
    draw_common_header(canvas, doc, report_data)
    draw_carescore(canvas, analysis_result)


def draw_later_pages(canvas, doc, report_data):
    draw_common_header(canvas, doc, report_data)


def generate_report_pdf(report_data, analysis_result):
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=55,
        rightMargin=55,
        topMargin=140,   
        bottomMargin=65
    )

    styles = getSampleStyleSheet()
    styles["Heading2"].textColor = colors.HexColor("#1f2937")
    styles["Heading2"].spaceBefore = 14
    styles["Heading2"].spaceAfter = 6
    styles["BodyText"].leading = 14

    story = []

    explanation = normalize_explanation(analysis_result.get("explanation"))
    if explanation:
        story.append(
            Paragraph(
                "Understanding Your Health Markers",
                styles["Heading2"]
            )
        )
        explanation = explanation.replace("\n\n", "<br/><br/>").replace("\n", "<br/>")
        story.append(Paragraph(explanation, styles["BodyText"]))
        story.append(Spacer(1, 16))

    deviations = analysis_result.get("deviations") or []
    if isinstance(deviations, dict):
        deviations = [
            f"{k.replace('_',' ').title()} ({v})"
            for k, v in deviations.items()
            if v != "normal"
        ]

    if deviations:
        story.append(Paragraph("Deviations Detected", styles["Heading2"]))
        for d in deviations:
            story.append(Paragraph(f"• {d}", styles["BodyText"]))
        story.append(Spacer(1, 16))


    tests = report_data.get("confirmed_data", {}).get("tests", [])
    if tests:
        story.append(Paragraph("Test Results", styles["Heading2"]))

        table_data = [["Test", "Value", "Unit", "Reference Range"]]
        for t in tests:
            table_data.append([
                t.get("test_name", "").replace("_", " ").title(),
                str(t.get("value", "")),
                t.get("unit", "—"),
                t.get("reference_range", "—")
            ])

        table = Table(table_data, colWidths=[160, 80, 80, 140])

        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),  
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONT", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

            ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [
                colors.HexColor("#f8fafc"),
                colors.HexColor("#eef2ff"),
            ]),

            ("GRID", (0, 0), (-1, -1), 0.75, colors.HexColor("#9ca3af")),

            ("ALIGN", (1, 1), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))


        story.append(table)
        story.append(Spacer(1, 20))

    chart = generate_biomarker_chart(tests)
    if chart:
        story.append(
            Paragraph(
                "Smart Health Visualization",
                styles["Heading2"]
            )
        )
        story.append(Image(chart, width=460, height=300))
        story.append(Spacer(1, 20))

    story.append(Spacer(1, 24))
    story.append(
        Paragraph(
            "<i>This report is AI-generated and not a medical diagnosis.</i>",
            styles["Italic"]
        )
    )

    doc.build(
        story,
        onFirstPage=lambda c, d: draw_first_page(c, d, report_data, analysis_result),
        onLaterPages=lambda c, d: draw_later_pages(c, d, report_data),
    )

    buffer.seek(0)
    return buffer
